In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
df=pd.DataFrame(load_breast_cancer().data, columns=load_breast_cancer().feature_names)
df['target'] = load_breast_cancer().target
df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [69]:
x=df.iloc[:, :-1].values
y=df.iloc[:, -1].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [70]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [71]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=25,metric='minkowski')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("Accuracy Score:", accuracy)

Confusion Matrix:
 [[39  4]
 [ 2 69]]
Accuracy Score: 0.9473684210526315


# Credit Risk Dataset

In [73]:
df=pd.read_csv('credit_risk_dataset.csv')
df.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [74]:
df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [75]:
df.describe()

person_age  person_income  person_emp_length     loan_amnt  \
count  32581.000000   3.258100e+04       31686.000000  32581.000000   
mean      27.734600   6.607485e+04           4.789686   9589.371106   
std        6.348078   6.198312e+04           4.142630   6322.086646   
min       20.000000   4.000000e+03           0.000000    500.000000   
25%       23.000000   3.850000e+04           2.000000   5000.000000   
50%       26.000000   5.500000e+04           4.000000   8000.000000   
75%       30.000000   7.920000e+04           7.000000  12200.000000   
max      144.000000   6.000000e+06         123.000000  35000.000000   

       loan_int_rate   loan_status  loan_percent_income  \
count   29465.000000  32581.000000         32581.000000   
mean       11.011695      0.218164             0.170203   
std         3.240459      0.413006             0.106782   
min         5.420000      0.000000             0.000000   
25%         7.900000      0.000000             0.090000   
50%        10.990000      0.000000             0.150000   
75%        13.470000      0.000000             0.230000   
max        23.220000      1.000000             0.830000   

       cb_person_cred_hist_length  
count                32581.000000  
mean                     5.804211  
std                      4.055001  
min                      2.000000  
25%                      3.000000  
50%                      4.000000  
75%                      8.000000  
max                     30.000000

In [76]:
df['cb_person_default_on_file'] = df['cb_person_default_on_file'].map({'Y':1, 'N':0})
df = pd.get_dummies(df,columns=['person_home_ownership','loan_intent','loan_grade'],drop_first=True)

In [77]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [78]:
df.isna().sum()

person_age                     0
person_income                  0
person_emp_length              0
loan_amnt                      0
loan_int_rate                  0
loan_status                    0
loan_percent_income            0
cb_person_default_on_file      0
cb_person_cred_hist_length     0
person_home_ownership_OTHER    0
person_home_ownership_OWN      0
person_home_ownership_RENT     0
loan_intent_EDUCATION          0
loan_intent_HOMEIMPROVEMENT    0
loan_intent_MEDICAL            0
loan_intent_PERSONAL           0
loan_intent_VENTURE            0
loan_grade_B                   0
loan_grade_C                   0
loan_grade_D                   0
loan_grade_E                   0
loan_grade_F                   0
loan_grade_G                   0
dtype: int64

In [79]:
x = df.drop('loan_status', axis=1)
y = df['loan_status']

In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=25, metric='minkowski')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(6517,))

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("Accuracy Score:", accuracy)

Confusion Matrix:
 [[4970  102]
 [ 595  850]]
Accuracy Score: 0.8930489489028695


In [82]:
k_values = range(1, 21)
accuracy_list = []
for k in k_values:
    acc = accuracy_score(y_test, y_pred)
    accuracy_list.append(acc)
for k, acc in zip(k_values, accuracy_list):
    print(f"K = {k} → Accuracy = {acc:.4f}")


K = 1 → Accuracy = 0.8930
K = 2 → Accuracy = 0.8930
K = 3 → Accuracy = 0.8930
K = 4 → Accuracy = 0.8930
K = 5 → Accuracy = 0.8930
K = 6 → Accuracy = 0.8930
K = 7 → Accuracy = 0.8930
K = 8 → Accuracy = 0.8930
K = 9 → Accuracy = 0.8930
K = 10 → Accuracy = 0.8930
K = 11 → Accuracy = 0.8930
K = 12 → Accuracy = 0.8930
K = 13 → Accuracy = 0.8930
K = 14 → Accuracy = 0.8930
K = 15 → Accuracy = 0.8930
K = 16 → Accuracy = 0.8930
K = 17 → Accuracy = 0.8930
K = 18 → Accuracy = 0.8930
K = 19 → Accuracy = 0.8930
K = 20 → Accuracy = 0.8930


In [86]:
new_customer = pd.DataFrame(columns=x.columns)
new_customer.loc[0] = 0
new_customer.loc[0, 'person_age'] = 30
new_customer.loc[0, 'person_income'] = 60000
new_customer.loc[0, 'person_emp_length'] = 5
new_customer.loc[0, 'loan_amnt'] = 15000
new_customer.loc[0, 'loan_int_rate'] = 13.5
new_customer.loc[0, 'loan_percent_income'] = 0.25
new_customer.loc[0, 'cb_person_default_on_file'] = 0
new_customer.loc[0, 'cb_person_cred_hist_length'] = 6
new_customer.loc[0, 'person_home_ownership_RENT'] = 1
new_customer.loc[0, 'loan_intent_MEDICAL'] = 1
new_customer.loc[0, 'loan_grade_C'] = 1
new_customer_scaled = scaler.transform(new_customer)
prediction = classifier.predict(new_customer_scaled)
if prediction[0] == 1:
    print("High Risk Customer")
else:
    print("Low Risk Customer")


Low Risk Customer


C:\Users\srira\AppData\Local\Temp\ipykernel_22024\3177534571.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '13.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_customer.loc[0, 'loan_int_rate'] = 13.5
C:\Users\srira\AppData\Local\Temp\ipykernel_22024\3177534571.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.25' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_customer.loc[0, 'loan_percent_income'] = 0.25


In [84]:
for k in [1, 3, 5, 7, 11, 15]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train, y_train)
    pred = knn.predict(new_customer_scaled)[0]

    result = "High Risk" if pred == 1 else "Low Risk"
    print(f"K = {k} → Prediction: {result}")


K = 1 → Prediction: Low Risk
K = 3 → Prediction: Low Risk
K = 5 → Prediction: Low Risk
K = 7 → Prediction: Low Risk
K = 11 → Prediction: Low Risk
K = 15 → Prediction: Low Risk


In [85]:
tn, fp, fn, tp = cm.ravel()

print("Correctly identified risky customers (TP):", tp)
print("Risky customers missed (FN):", fn)
print("Safe customers misclassified as risky (FP):", fp)
print("Correctly identified safe customers (TN):", tn)


Correctly identified risky customers (TP): 850
Risky customers missed (FN): 595
Safe customers misclassified as risky (FP): 102
Correctly identified safe customers (TN): 4970
